import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { Script } from "node:vm";

const htmlUrl = new URL("../src/control-panel/index.html", import.meta.url);
const scriptUrl = new URL("../src/control-panel/app.js", import.meta.url);
const themeScriptUrl = new URL("../src/control-panel/theme.js", import.meta.url);
const cssUrl = new URL("../src/control-panel/app.css", import.meta.url);
const mainUrl = new URL("../../src/main.ts", import.meta.url);

test("control-panel settings use typed controls instead of one raw config textarea", async () => {
  const [html, script, themeScript, css, main] = await Promise.all([readFile(htmlUrl, "utf8"), readFile(scriptUrl, "utf8"), readFile(themeScriptUrl, "utf8"), readFile(cssUrl, "utf8"), readFile(mainUrl, "utf8")]);

  assert.match(html, /id="configForm"/);
  assert.doesNotMatch(html, /id="config-secrets"|id="secretForm"|id="saveSecrets"/);
  assert.doesNotMatch(html, /<textarea id="config"/);
  assert.doesNotMatch(html, /查看 API 可用模型/);
  assert.doesNotThrow(() => new Script(script));
  assert.doesNotThrow(() => new Script(themeScript));
  assert.match(html, /<script src="theme\.js"><\/script>\s*<link rel="stylesheet" href="app\.css">/);
  assert.match(html, /<fieldset id="themeMode"[\s\S]*value="light"[\s\S]*value="system"[\s\S]*value="dark"/);
  assert.match(themeScript, /prefers-color-scheme: dark/);
  assert.match(themeScript, /localStorage\.umiroTheme/);
  assert.match(css, /:root\s*\{[\s\S]*color-scheme: light/);
  assert.match(css, /:root\[data-theme="dark"\]\s*\{[\s\S]*color-scheme: dark/);
  assert.match(script, /path: 'model', type: 'model'/);
  assert.match(script, /input\.type = 'radio'/);
  assert.match(script, /path: 'embedding\.baseUrl', type: 'secret'/);
  assert.match(script, /path: 'embedding\.baseUrl', type: 'secret', inputType: 'url'/);
  assert.match(script, /title: '模型與 Context'[\s\S]*?secretName: 'LLM_BASE_URL'[\s\S]*?secretName: 'LLM_API_KEY'/);
  assert.match(script, /connectModels: true/);
  assert.match(script, /api\('\/api\/models\/discover', \{ method: 'POST'/);
  assert.match(script, /showToast\('連接成功，共取得 '/);
  assert.match(css, /\.provider-connect/);
  assert.match(script, /classList\.add\('config-checkbox-label'\)/);
  assert.match(script, /subgroup\.className = 'config-subgroup config-wide'/);
  assert.match(css, /\.config-checkbox-label \{[^}]*inline-flex/);
  assert.match(css, /\.config-subgroup \{[^}]*border:/);
  assert.match(css, /\.config-subgroup\[hidden\] \{ display: none; \}/);
  assert.match(script, /title: 'Discord'[\s\S]*?secretName: 'DISCORD_TOKEN'[\s\S]*?secretName: 'UMIRO_OWNER_DISCORD_ID'/);
  assert.match(script, /path: 'conversation\.autoArchive\.enabled', type: 'checkbox'/);
  assert.match(script, /path: 'conversation\.autoArchive\.time', type: 'time'/);
  assert.match(script, /path: 'conversation\.autoArchive\.timezone', type: 'text'/);
  assert.match(script, /subgroup: 'conversation-auto-archive'/);
  assert.match(script, /preserveWhenHidden: true/);
  assert.match(script, /每天指定時間後會封存各 Discord 頻道/);
  assert.doesNotMatch(script, /UMIRO_WEB_UI_TOKEN/);
  const editableSecrets = main.slice(main.indexOf("const editableSecretNames"), main.indexOf("const persistSecrets"));
  assert.match(editableSecrets, /editableSecretNames\.delete\("UMIRO_WEB_UI_TOKEN"\)/);
  assert.doesNotMatch(script, /\$\('config-embedding-baseUrl'\)\.value = ''/);
  assert.match(script, /const secretFields = configFields\(\)\.filter\(field => field\.type === 'secret'\)/);
  assert.match(script, /if \(!field\.publicValue\) control\.value = ''/);
  assert.match(script, /field\.type === 'model' && models\.length === 0/);
  assert.match(script, /document\.createElement\('select'\)/);
  assert.match(script, /className = 'config-tooltip'/);
  assert.match(script, /config-restart-required/);
  assert.doesNotMatch(script, /儲存後需重啟|儲存後即時生效/);
  assert.match(html, /class="config-restart-legend">此顏色的欄位名稱需重啟/);
  assert.match(css, /--restart-required:/);
  assert.match(html, /id="toastRegion"/);
  assert.match(html, /id="modalBackdrop"/);
  assert.match(html, /id="configSearch"/);
  assert.match(html, /id="runtimeCards"/);
  assert.match(html, /id="documentPreview"/);
  assert.match(html, /id="scheduleTime" type="time"/);
  assert.doesNotMatch(html, /id="scheduleHour"|id="scheduleMinute"/);
  assert.match(script, /Number\(minute\) \+ ' ' \+ Number\(hour\)/);
  assert.match(script, /if \(button\.textContent === busyText\) button\.textContent = original/);
  const scheduleReset = script.slice(script.indexOf("function resetScheduleForm"), script.indexOf("let previewTimer"));
  for (const id of ["scheduleName", "scheduleWhen", "schedulePrompt", "scheduleChannel", "scheduleChannelId"]) assert.match(scheduleReset, new RegExp(`\\$\\('${id}'\\)\\.value = ''`));
  assert.match(scheduleReset, /editingSchedule = undefined/);
  assert.match(scheduleReset, /\$\('scheduleKind'\)\.value = 'cron'/);
  assert.match(scheduleReset, /\$\('scheduleFrequency'\)\.value = 'daily'/);
  assert.match(scheduleReset, /\$\('scheduleTime'\)\.value = '09:00'/);
  assert.match(scheduleReset, /updateScheduleControls\(\)/);
  assert.match(script, /resetScheduleForm\(\);\s*await schedules\(\)/);
  assert.match(script, /await pluginAction\('install',[\s\S]*?\$\('pluginSource'\)\.value = ''; \$\('pluginWorkspace'\)\.value = '';/);
  assert.match(script, /configSchema/);
  assert.match(script, /requiredSecrets/);
  assert.match(script, /optionalSecrets/);
  assert.match(script, /data-plugin-secret-key/);
  assert.match(script, /只會儲存在 secrets\.env，不會回顯/);
  const pluginUi = script.slice(script.indexOf("async function pluginAction"), script.indexOf("function sourceBaseName"));
  assert.match(pluginUi, /const payload = \{ action, source, workspace, config \};/);
  assert.match(pluginUi, /if \(action === 'remove' && removeSecrets === true\) payload\.removeSecrets = true;/);
  assert.match(pluginUi, /JSON\.stringify\(payload\)/);
  assert.doesNotMatch(pluginUi, /JSON\.parse\(basePayload\)/);
  assert.match(pluginUi, /await api\('\/api\/secrets', \{ method: 'PUT', body: JSON\.stringify\(secrets\) \}\)/);
  assert.match(pluginUi, /const secrets = Object\.fromEntries\(\[\.\.\.body\.querySelectorAll\('\[data-plugin-secret-key\]'\)[\s\S]*?filter\(\(\[, value\]\) => value\)\)/);
  assert.match(pluginUi, /filter\(\(\[name\]\) => !secretNames\.has\(name\)\)/);
  assert.match(pluginUi, /markPluginSecretsConfigured\(body, new Set\(Object\.keys\(secrets\)\)\)/);
  assert.match(pluginUi, /control\.value = '';[\s\S]*control\.placeholder = '已設定；留空不變'/);
  assert.match(pluginUi, /await api\('\/api\/plugins\/action'[\s\S]*await plugins\(\)/);
  const removeModal = script.slice(script.indexOf("async function confirmPluginRemoval"), script.indexOf("function renderPluginRow"));
  assert.match(removeModal, /dataset\.removePluginSecrets/);
  assert.match(removeModal, /control\.checked = false/);
  assert.match(removeModal, /\.filter\(name => typeof name === 'string' && secretStatus\[name\]\)/);
  assert.match(removeModal, /停用不會刪除 Secret；其他外掛共用或 ümiro 核心 Secret 會保留/);
  assert.doesNotMatch(pluginUi, /required\s*=\s*true/);
  assert.match(script, /\/api\/schedules\/preview/);
  assert.match(script, /\/api\/runtime\/restart/);
  assert.match(html, /id="pluginRestartNotice"[^>]*hidden/);
  assert.match(html, /id="restartPlugins"[^>]*>立即重啟<\/button>/);
  assert.match(script, /function markPluginRestartRequired[\s\S]*?pluginRestartNotice[\s\S]*?hidden = false/);
  assert.match(script, /restartPlugins'\)\.onclick = restartGateway/);
  assert.match(script, /pluginRestartNotice'\)\.hidden = true/);
  assert.doesNotMatch(script, /\balert\(|\bprompt\(/);
  assert.match(script, /api\('\/api\/secrets', \{ method: 'PUT'/);
  assert.match(script, /await r\.text\(\)/);
  assert.match(script, /無法連線到 ümiro Gateway/);
});
