import assert from "node:assert/strict";
import { access, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createPlugin } from "../src/index.js";

test("built-in context provider loads OWNER with the other workspace files", async () => {
  const root = await mkdtemp(join(tmpdir(), "umiro-context-"));
  for (const [name, content] of [["SOUL.md", "soul"], ["AGENT.md", "agent"], ["OWNER.md", "owner"], ["MEMORY.md", "memory"]] as const) await writeFile(join(root, name), content);
  const plugin = createPlugin({ pluginId: "context-files", namespace: "context-files", permissionCeiling: { capabilities: [], visibility: { kind: "all" }, instructionAuthority: "none" }, config: { workspacePath: root }, getSecret: () => undefined });
  await plugin.start?.();
  const providers = plugin.contributions.contextProviders ?? [];
  assert.deepEqual(providers.map(provider => provider.id), ["context.bootstrap", "context.soul", "context.agent", "context.owner", "context.memory", "context.conversation_history"]);
  const request = { runId: "run", execution: { actor: { id: "owner", kind: "human", roles: ["owner"] } } as never, prompt: "hi" };
  const owner = await providers.find(provider => provider.id === "context.owner")!.load(request);
  assert.equal(owner[0]?.content, "owner");
  const ownerTools = plugin.contributions.tools ?? [];
  const add = ownerTools.find(tool => tool.name === "owner_profile_add")!;
  const replace = ownerTools.find(tool => tool.name === "owner_profile_replace")!;
  assert.equal((await add.execute({ content: "稱呼：主人" }, {} as never) as { ok: boolean }).ok, true);
  assert.match(await (await import("node:fs/promises")).readFile(join(root, "OWNER.md"), "utf8"), /稱呼：主人/);
  assert.equal((await replace.execute({ oldText: "稱呼：主人", newText: "稱呼：Owner" }, {} as never) as { ok: boolean }).ok, true);
  const history = await providers.find(provider => provider.id === "context.conversation_history")!.load({ ...request, conversationCompaction: { conversationId: "c", throughSequence: 3, sourceHash: "abc", summary: "先前談過授權邊界", updatedAt: "now" }, recentHistory: [{ turn: { id: "t", conversationId: "c", sequence: 4, actorPrincipalId: "user", inputEventId: "e", content: [{ type: "text", text: "我叫小明" }], createdAt: "now" }, assistantText: "記住了" }] });
  assert.deepEqual(history.map(block => block.id), ["context.conversation_history:compacted", "context.conversation_history:recent"]);
  assert.match(history[0]?.content ?? "", /先前談過授權邊界/);
  assert.match(history[1]?.content ?? "", /我叫小明[\s\S]*記住了/);
  const reply = await providers.find(provider => provider.id === "context.conversation_history")!.load({ ...request, replyTarget: { turn: { id: "reply-turn", conversationId: "c", sequence: 1, actorPrincipalId: "user", inputEventId: "e-reply", content: [{ type: "text", text: "被回覆的內容" }], createdAt: "now" }, assistantText: "原本的回答" } });
  assert.match(reply[0]?.content ?? "", /discord-reply-target[\s\S]*被回覆的內容[\s\S]*原本的回答/);
  const fetchedReply = await providers.find(provider => provider.id === "context.conversation_history")!.load({ ...request, inputEvent: { metadata: { replyToMessageId: "discord-message-1", replyAuthorId: "member-1", replyToContent: "尚未入庫的被回覆訊息" } } as never });
  assert.match(fetchedReply[0]?.content ?? "", /external-message-id="discord-message-1"[\s\S]*尚未入庫的被回覆訊息/);
  await plugin.stop?.();
});

test("bootstrap is owner-only and disappears after both identity files leave shipped templates", async () => {
  const root = await mkdtemp(join(tmpdir(), "umiro-bootstrap-"));
  await writeFile(join(root, "SOUL.md"), "# SOUL\n");
  await writeFile(join(root, "OWNER.md"), "# OWNER\n");
  await writeFile(join(root, "AGENT.md"), "agent\n");
  await writeFile(join(root, "MEMORY.md"), "memory\n");
  const plugin = createPlugin({ pluginId: "context-files", namespace: "context-files", permissionCeiling: { capabilities: [], visibility: { kind: "all" }, instructionAuthority: "none" }, config: { workspacePath: root }, getSecret: () => undefined });
  await plugin.start?.();
  await writeFile(join(root, "BOOTSTRAP.md"), "setup\n");
  const bootstrap = plugin.contributions.contextProviders!.find(provider => provider.id === "context.bootstrap")!;
  assert.equal((await bootstrap.load({ runId: "r", execution: { actor: { id: "member", kind: "human", roles: [] } } as never, prompt: "hi" })).length, 0);
  assert.equal((await bootstrap.load({ runId: "r", execution: { actor: { id: "owner", kind: "human", roles: ["owner"] } } as never, prompt: "hi" }))[0]?.content, "setup\n");
  await writeFile(join(root, "SOUL.md"), "# SOUL\nChosen voice\n");
  await writeFile(join(root, "OWNER.md"), "# OWNER\nChosen owner\n");
  await plugin.start?.();
  await assert.rejects(access(join(root, "BOOTSTRAP.md")));
  await plugin.stop?.();
});
