import { lstat, realpath } from "node:fs/promises";
import { relative, resolve, sep } from "node:path";
import type { JsonObject } from "@umiro/core/ports";
import type { PluginInstance, PluginSetupContext } from "@umiro/core/plugin";
import type { ToolDefinition, ToolExecutionContext, ToolExecutionResult } from "@umiro/core/tool";

const failure = (error: unknown): ToolExecutionResult => ({ ok: false, effectStatus: "not_applicable", error: { code: "discord_tool_error", message: error instanceof Error ? error.message : String(error), retryable: false } });
const success = (output: unknown): ToolExecutionResult => ({ ok: true, effectStatus: "confirmed", output: output as never });

function channel(input: JsonObject): string { const value = input.channelId; if (typeof value !== "string" || !/^[0-9]{2,32}$/.test(value)) throw new TypeError("channelId must be a Discord snowflake"); return value; }
function message(input: JsonObject): string { const value = input.messageId; if (typeof value !== "string" || !/^[0-9]{2,32}$/.test(value)) throw new TypeError("messageId must be a Discord snowflake"); return value; }
function resource(input: JsonObject) { return { kind: "discord-channel", id: channel(input) }; }
function define(definition: Omit<ToolDefinition, "execute"> & { execute: (input: JsonObject, context: ToolExecutionContext) => Promise<unknown> }): ToolDefinition {
  return { ...definition, async execute(input, context) { try { const result = success(await definition.execute(input, context)); return definition.policy.sideEffect === "none" ? { ...result, effectStatus: "not_applicable" } : result; } catch (error) { return failure(error); } } };
}
const channelMessageSchema = { type: "object", additionalProperties: false, required: ["channelId", "messageId"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" } } };

export function createPlugin(setup: PluginSetupContext): PluginInstance {
  const service = () => { const value = setup.services?.discord; if (!value) throw new Error("Discord operation service is unavailable"); return value; };
  const workspacePath = typeof setup.config.workspacePath === "string" ? resolve(setup.config.workspacePath, "attachments") : undefined;
  const artifactService = () => { const value = setup.services?.artifacts; if (!value) throw new Error("Artifact service is unavailable"); return value; };
  const workspaceFile = async (input: JsonObject): Promise<string> => {
    if (!workspacePath) throw new Error("discord-tools workspacePath is not configured");
    if (typeof input.file !== "string" || !input.file.trim()) throw new TypeError("file is required");
    const file = await realpath(resolve(workspacePath, input.file));
    const attachmentsPath = resolve(workspacePath, "attachments");
    const relativePath = relative(attachmentsPath, file);
    if (!relativePath || relativePath === ".." || relativePath.startsWith(`..${sep}`)) throw new Error("file must be inside workspace attachments");
    const metadata = await lstat(file);
    if (metadata.isSymbolicLink() || !metadata.isFile()) throw new Error("attachment must be a regular file");
    return file;
  };
  const tools: ToolDefinition[] = [
    define({ name: "discord_send_message", description: "Send a message to an explicitly identified Discord channel.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "content"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, content: { type: "string", minLength: 1, maxLength: 2_000 } } }, policy: { capability: "discord.message.write", tier: "common", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { return service().sendMessage({ channelId: channel(input), content: String(input.content), signal: context.signal }); } }),
    define({ name: "discord_react", description: "Add a reaction to an explicitly identified Discord message.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "messageId", "emoji"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" }, emoji: { type: "string", minLength: 1, maxLength: 64 } } }, policy: { capability: "discord.message.react", tier: "common", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().react({ channelId: channel(input), messageId: message(input), emoji: String(input.emoji), signal: context.signal }); return { reacted: true }; } }),
    define({ name: "discord_pin", description: "Pin an explicitly identified Discord message.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "messageId"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" } } }, policy: { capability: "discord.message.pin", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().pin({ channelId: channel(input), messageId: message(input), signal: context.signal }); return { pinned: true }; } }),
    define({ name: "discord_unpin", description: "Unpin an explicitly identified Discord message.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "messageId"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" } } }, policy: { capability: "discord.message.pin", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().unpin({ channelId: channel(input), messageId: message(input), signal: context.signal }); return { unpinned: true }; } }),
    define({ name: "discord_fetch_message", description: "Fetch one explicitly identified Discord message.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "messageId"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" } } }, policy: { capability: "discord.message.read", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "none", resource }, async execute(input, context) { return service().fetchMessage({ channelId: channel(input), messageId: message(input), signal: context.signal }); } }),
    define({ name: "discord_create_thread", description: "Create a thread in an explicitly identified Discord channel.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "name"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, name: { type: "string", minLength: 1, maxLength: 100 }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" } } }, policy: { capability: "discord.thread.write", tier: "common", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { return service().createThread({ channelId: channel(input), name: String(input.name), ...(typeof input.messageId === "string" ? { messageId: message(input) } : {}), signal: context.signal }); } }),
    define({ name: "discord_create_forum_post", description: "Create a new post in the Discord Forum identified by the channel ID. If the user says 'this/current Forum', use the trusted currentForum.id from Discord context; if the user supplies another ID, use that ID. Never silently replace an explicit target.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "title", "content"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$", description: "Target Discord Forum channel ID: use currentForum.id for 'this/current Forum', or the other ID supplied by the user." }, title: { type: "string", minLength: 1, maxLength: 100 }, content: { type: "string", minLength: 1, maxLength: 2_000 } } }, policy: { capability: "discord.thread.write", tier: "common", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { return service().createForumPost({ channelId: channel(input), title: String(input.title), content: String(input.content), signal: context.signal }); } }),
    define({ name: "discord_rename_post", description: "Rename an explicitly identified Discord forum post or thread. For the current post, use currentPost.id from trusted Discord context as threadId.", inputSchema: { type: "object", additionalProperties: false, required: ["threadId", "name"], properties: { threadId: { type: "string", pattern: "^[0-9]{2,32}$", description: "Discord thread ID; use currentPost.id for the current forum post." }, name: { type: "string", minLength: 1, maxLength: 100, description: "New post or thread name" } } }, policy: { capability: "discord.thread.write", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource: input => ({ kind: "discord-channel", id: String(input.threadId) }) }, async execute(input, context) { await service().renameThread({ threadId: String(input.threadId), name: String(input.name), signal: context.signal }); return { renamed: true, threadId: input.threadId, name: input.name }; } }),
    define({ name: "discord_rename_forum", description: "Rename an explicitly identified Discord Forum channel. For the current Forum, use currentForum.id from trusted Discord context as channelId.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "name"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$", description: "Discord Forum channel ID; use currentForum.id for the current Forum." }, name: { type: "string", minLength: 1, maxLength: 100, description: "New Forum name" } } }, policy: { capability: "discord.thread.write", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().renameForum({ channelId: channel(input), name: String(input.name), signal: context.signal }); return { renamed: true, channelId: input.channelId, name: input.name }; } }),
    define({ name: "discord_archive_thread", description: "Archive an explicitly identified Discord thread.", inputSchema: channelMessageSchema, policy: { capability: "discord.thread.write", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().archiveThread({ channelId: channel(input), threadId: message(input), signal: context.signal }); return { archived: true }; } }),
    define({ name: "discord_delete_thread", description: "Delete an explicitly identified Discord thread.", inputSchema: channelMessageSchema, policy: { capability: "discord.thread.delete", tier: "privileged", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { await service().deleteThread({ channelId: channel(input), threadId: message(input), signal: context.signal }); return { deleted: true }; } }),
    define({ name: "discord_edit_message", description: "Edit an explicitly identified Discord message.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "messageId", "content"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, messageId: { type: "string", pattern: "^[0-9]{2,32}$" }, content: { type: "string", minLength: 1, maxLength: 2_000 } } }, policy: { capability: "discord.message.write", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "idempotent", resource }, async execute(input, context) { await service().editMessage({ channelId: channel(input), messageId: message(input), content: String(input.content), signal: context.signal }); return { edited: true }; } }),
    define({ name: "discord_delete_message", description: "Delete an explicitly identified Discord message.", inputSchema: channelMessageSchema, policy: { capability: "discord.message.delete", tier: "privileged", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { await service().deleteMessage({ channelId: channel(input), messageId: message(input), signal: context.signal }); return { deleted: true }; } }),
    define({ name: "discord_fetch_channel_messages", description: "Fetch a bounded set of messages from an explicitly identified Discord channel.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, limit: { type: "integer", minimum: 1, maximum: 100 } } }, policy: { capability: "discord.message.read", tier: "sensitive", interactionRequirement: "not_required", sideEffect: "none", resource }, async execute(input, context) { return service().fetchChannelMessages({ channelId: channel(input), limit: typeof input.limit === "number" ? input.limit : 50, signal: context.signal }); } }),
    define({ name: "discord_bot_mention_toggle", description: "Enable or disable responses to messages sent by other bots. Guild and channel allowlists still apply.", inputSchema: { type: "object", additionalProperties: false, required: ["enabled"], properties: { enabled: { type: "boolean" } } }, policy: { capability: "discord.policy.write", tier: "privileged", interactionRequirement: "not_required", sideEffect: "idempotent" }, async execute(input) { const enabled = input.enabled === true; await service().setRespondToBots(enabled); return { respondToBots: enabled }; } }),
    { name: "discord_attach_to_reply", description: "Attach a workspace/attachments file to the current final Discord reply.", inputSchema: { type: "object", additionalProperties: false, required: ["file"], properties: { file: { type: "string", minLength: 1 }, filename: { type: "string", minLength: 1, maxLength: 120 }, mediaType: { type: "string", minLength: 1, maxLength: 200 } } }, policy: { capability: "discord.attachment.write", tier: "privileged", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource: input => ({ kind: "workspace", id: "attachments" }) }, async execute(input, context) { try { const file = await workspaceFile(input); const artifact = await artifactService().createFromWorkspaceFile({ sourcePath: file, ownerPrincipalId: context.execution.actor.id, ...(typeof input.filename === "string" ? { filename: input.filename } : {}), ...(typeof input.mediaType === "string" ? { mediaType: input.mediaType } : {}), parentSource: { kind: "operation", id: context.operationId } }); return { ok: true, effectStatus: "confirmed", output: { artifactId: artifact.id, filename: artifact.filename ?? file.split(/[\\/]/).pop() ?? "attachment" }, artifactIds: [artifact.id] }; } catch (error) { return failure(error); } } },
    define({ name: "discord_send_buttons", description: "Send a Discord message with durable configurable action buttons.", inputSchema: { type: "object", additionalProperties: false, required: ["channelId", "content", "buttons"], properties: { channelId: { type: "string", pattern: "^[0-9]{2,32}$" }, content: { type: "string", minLength: 1, maxLength: 2_000 }, allowedUserIds: { type: "array", uniqueItems: true, maxItems: 100, items: { type: "string", pattern: "^[0-9]{2,32}$" } }, expiresInMinutes: { type: "integer", minimum: 1, maximum: 10080 }, buttons: { type: "array", minItems: 1, maxItems: 25, items: { type: "object", additionalProperties: false, required: ["id", "label", "style", "actionTool", "actionArgs"], properties: { id: { type: "string", pattern: "^[A-Za-z0-9_-]{1,32}$" }, label: { type: "string", minLength: 1, maxLength: 80 }, style: { type: "string", enum: ["primary", "secondary", "success", "danger"] }, actionTool: { type: "string", minLength: 1, maxLength: 100 }, actionArgs: { type: "object" } } } } } }, policy: { capability: "discord.button.write", tier: "privileged", interactionRequirement: "not_required", sideEffect: "non_idempotent", resource }, async execute(input, context) { const buttons = input.buttons as Array<Record<string, unknown>>; const defaultUser = context.execution.actor.identities?.find(identity => identity.transport === "discord")?.externalId; const allowedUserIds = Array.isArray(input.allowedUserIds) ? input.allowedUserIds as string[] : defaultUser ? [defaultUser] : []; if (allowedUserIds.length === 0) throw new Error("allowedUserIds is required when the creator has no Discord identity"); const actionButtons = buttons.map(button => ({ id: String(button.id), label: String(button.label), style: String(button.style) as "primary" | "secondary" | "success" | "danger", actionTool: String(button.actionTool), actionArgs: button.actionArgs as JsonObject })); return service().createButtonSet({ channelId: channel(input), content: String(input.content), allowedUserIds, ...(typeof input.expiresInMinutes === "number" ? { expiresInMinutes: input.expiresInMinutes } : {}), creatorPrincipalId: context.execution.actor.id, buttons: actionButtons, signal: context.signal }); } }),
  ];
  return { contributions: { tools } };
}
