import type { JsonObject } from "@umiro/core/ports";
import type { PluginInstance, PluginSetupContext } from "@umiro/core/plugin";
import type { ToolDefinition, ToolExecutionContext, ToolExecutionResult } from "@umiro/core/tool";

const ok = (output: unknown): ToolExecutionResult => ({ ok: true, output: output as never, effectStatus: "confirmed" });
const fail = (error: unknown): ToolExecutionResult => ({ ok: false, effectStatus: "not_applicable", error: { code: "scheduler_error", message: error instanceof Error ? error.message : String(error), retryable: false } });

export function createPlugin(setup: PluginSetupContext): PluginInstance {
  const scheduler = setup.services?.scheduler; if (!scheduler) throw new Error("scheduler service is unavailable");
  const config = setup.config as { timezone?: string; model?: string };
  const define = (definition: Omit<ToolDefinition, "execute"> & { execute: (input: JsonObject, context: ToolExecutionContext) => Promise<unknown> }): ToolDefinition => ({ ...definition, async execute(input, context) { try { return ok(await definition.execute(input, context)); } catch (error) { return fail(error); } } });
  const create = async (input: JsonObject, context: ToolExecutionContext, schedule: { kind: "cron"; expression: string } | { kind: "once"; at: string }) => {
    const destination = typeof input.channelId === "string" && input.channelId ? { kind: "discord", channelId: input.channelId } : undefined;
    return scheduler.create({ name: String(input.name), enabled: true, schedule, timezone: typeof input.timezone === "string" ? input.timezone : (config.timezone ?? "Asia/Taipei"), jobRef: "agent.prompt", input: { prompt: String(input.prompt), ...(config.model ? { model: config.model } : {}) }, creatorPrincipalId: context.execution.actor.id, creatorRoles: context.execution.actor.roles, authority: context.execution.authority, ...(destination ? { destination } : {}), misfirePolicy: typeof input.misfirePolicy === "string" ? input.misfirePolicy as "catch_up" | "coalesce" | "skip" : "coalesce", maxAttempts: 3, retryBackoffMs: 15_000 }, context.idempotencyKey);
  };
  const common = { interactionRequirement: "not_required" as const };
  return { contributions: { tools: [
    define({ name: "cron_create", description: "Create a durable recurring agent task. Discord destination is optional.", inputSchema: { type: "object", additionalProperties: false, required: ["name", "schedule", "prompt"], properties: { name: { type: "string", minLength: 1 }, schedule: { type: "string", minLength: 1 }, prompt: { type: "string", minLength: 1 }, timezone: { type: "string" }, channelId: { type: "string" }, misfirePolicy: { enum: ["catch_up", "coalesce", "skip"] } } }, policy: { capability: "scheduler.write", tier: "common", ...common, sideEffect: "idempotent" }, execute: (input, context) => create(input, context, { kind: "cron", expression: String(input.schedule) }) }),
    define({ name: "reminder_create", description: "Create a durable one-shot agent reminder at an ISO timestamp. Discord destination is optional.", inputSchema: { type: "object", additionalProperties: false, required: ["name", "at", "prompt"], properties: { name: { type: "string", minLength: 1 }, at: { type: "string", minLength: 1 }, prompt: { type: "string", minLength: 1 }, timezone: { type: "string" }, channelId: { type: "string" } } }, policy: { capability: "scheduler.write", tier: "common", ...common, sideEffect: "idempotent" }, execute: (input, context) => create(input, context, { kind: "once", at: String(input.at) }) }),
    define({ name: "schedule_list", description: "List durable scheduled tasks.", inputSchema: { type: "object", additionalProperties: false, properties: {} }, policy: { capability: "scheduler.read", tier: "common", ...common, sideEffect: "none" }, async execute(_input, context) { const all = await scheduler.list(); return { triggers: all.filter(trigger => context.execution.actor.roles.includes("owner") || trigger.creatorPrincipalId === context.execution.actor.id) }; } }),
    define({ name: "schedule_toggle", description: "Enable or disable a durable scheduled task.", inputSchema: { type: "object", additionalProperties: false, required: ["id", "enabled"], properties: { id: { type: "string" }, enabled: { type: "boolean" } } }, policy: { capability: "scheduler.write", tier: "privileged", ...common, sideEffect: "idempotent" }, async execute(input, context) { const existing = (await scheduler.list()).find(trigger => trigger.id === input.id); if (!existing || (!context.execution.actor.roles.includes("owner") && existing.creatorPrincipalId !== context.execution.actor.id)) throw new Error("scheduled task not found"); return scheduler.setEnabled(String(input.id), input.enabled === true); } }),
    define({ name: "schedule_update", description: "Edit an existing scheduled task without changing its durable identity.", inputSchema: { type: "object", additionalProperties: false, required: ["id", "name", "schedule", "prompt"], properties: { id: { type: "string" }, name: { type: "string", minLength: 1 }, schedule: { type: "string", minLength: 1 }, prompt: { type: "string", minLength: 1 }, timezone: { type: "string" }, channelId: { type: "string" } } }, policy: { capability: "scheduler.write", tier: "privileged", ...common, sideEffect: "idempotent" }, async execute(input, context) { const existing = (await scheduler.list()).find(trigger => trigger.id === input.id); if (!existing || (!context.execution.actor.roles.includes("owner") && existing.creatorPrincipalId !== context.execution.actor.id) || !scheduler.update) throw new Error("scheduled task update unavailable"); return scheduler.update(String(input.id), { name: String(input.name), schedule: existing.schedule.kind === "once" ? { kind: "once", at: String(input.schedule) } : { kind: "cron", expression: String(input.schedule) }, timezone: typeof input.timezone === "string" ? input.timezone : existing.timezone, input: { ...existing.input, prompt: String(input.prompt) }, ...(typeof input.channelId === "string" && input.channelId ? { destination: { kind: "discord", channelId: input.channelId } } : existing.destination ? { destination: existing.destination } : {}), misfirePolicy: existing.misfirePolicy, maxAttempts: existing.maxAttempts, retryBackoffMs: existing.retryBackoffMs }); } }),
    define({ name: "schedule_delete", description: "Delete a durable scheduled task. Owner only.", inputSchema: { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string" } } }, policy: { capability: "scheduler.remove", tier: "privileged", ...common, sideEffect: "idempotent" }, async execute(input) { return { removed: await scheduler.remove(String(input.id)) }; } }),
  ] } };
}
